//GENERAL
export const CONNECTED = 'CONNECTED';
export const DISCONNECTED = 'DISCONNECTED';
export const INCOMING_MESSAGE = 'INCOMING_MESSAGE';

//GUEST
export const IDENTIFY_GUEST = 'IDENTIFY_GUEST';
export const IDENTIFYING_GUEST_SUCCEEDED = 'IDENTIFYING_GUEST_SUCCEEDED';
export const IDENTIFYING_GUEST_FAILED = 'IDENTIFYING_GUEST_FAILED';
export const CHAT_LICENSE_ERROR = 'CHAT_LICENSE_ERROR';